export const Tabledata = [
  {
    id: 310,
    regId: "0310",
    regShortName: "Wiretap Act",
    cfrRef: "",
    regLongName: "Electronic Communications Privacy Act",
    regDescription:
      "The Electronic Communications Privacy Act (“ECPA”) was passed in 1986 to expand and revise federal wiretapping and electronic eavesdropping provisions. It was enacted to create promote ” the privacy expectations of citizens and the legitimate needs of law enforcement.” Congress also sought to support the creation of new technologies by assuring consumers that their personal information would remain safe.",
    regUrl: "https://www.law.cornell.edu/uscode/text/18/2511",
    regComplianceGuideUrl: "",
    regRelatedLaw: "Electronic Communications Privacy Act of 1986",
    regEffectiveDate: null,
    regAuthoringRegulator: "USLEG",
    regPrimarySupervisor: "DOJ",
    status: true,
    createdDate: "2023-06-23T13:45:38.000Z",
    updatedDate: null,
    regulator: {
      id: 16,
      regulatorShortName: "USLEG",
      regulatorLongName: "US Legislature",
      regulatorDesc: "",
      regulatorMainUrl: "",
      regulatorUpdateSource: "",
      regulatorUpdateContact: "",
      country: "US",
      state: "All",
      county: "",
      status: true,
      createdDate: "2023-06-23T13:44:36.000Z",
      updatedDate: null,
    },
  },
  {
    id: 309,
    regId: "0309",
    regShortName: "Volcker Amendment",
    cfrRef: "",
    regLongName: "Volcker Amendment",
    regDescription:
      "The Volcker Rule is a federal regulation that generally prohibits banks from conducting certain investment activities with their own accounts and limits their dealings with hedge funds and private equity funds, also called covered funds.",
    regUrl: "https://www.law.cornell.edu/uscode/text/12/1851",
    regComplianceGuideUrl: "",
    regRelatedLaw: "Volcker Rule",
    regEffectiveDate: null,
    regAuthoringRegulator: "USLEG",
    regPrimarySupervisor: "OCC",
    status: true,
    createdDate: "2023-06-23T13:45:38.000Z",
    updatedDate: null,
    regulator: {
      id: 16,
      regulatorShortName: "USLEG",
      regulatorLongName: "US Legislature",
      regulatorDesc: "",
      regulatorMainUrl: "",
      regulatorUpdateSource: "",
      regulatorUpdateContact: "",
      country: "US",
      state: "All",
      county: "",
      status: true,
      createdDate: "2023-06-23T13:44:36.000Z",
      updatedDate: null,
    },
  },
  {
    id: 308,
    regId: "0308",
    regShortName: "Veterans Affairs (VA)",
    cfrRef: "",
    regLongName: "Veterans Affairs",
    regDescription:
      "(specifically Refi Comparison and Escape Clause) The United States Department of Veterans Affairs is a Cabinet-level executive branch department of the federal government charged with providing life-long services to eligible military veterans.",
    regUrl: "Two different URLs (pdf guides)",
    regComplianceGuideUrl: "",
    regRelatedLaw: "Executive Order 5398",
    regEffectiveDate: null,
    regAuthoringRegulator: "USLEG",
    regPrimarySupervisor: "VA",
    status: true,
    createdDate: "2023-06-23T13:45:38.000Z",
    updatedDate: null,
    regulator: {
      id: 16,
      regulatorShortName: "USLEG",
      regulatorLongName: "US Legislature",
      regulatorDesc: "",
      regulatorMainUrl: "",
      regulatorUpdateSource: "",
      regulatorUpdateContact: "",
      country: "US",
      state: "All",
      county: "",
      status: true,
      createdDate: "2023-06-23T13:44:36.000Z",
      updatedDate: null,
    },
  },
  {
    id: 307,
    regId: "0307",
    regShortName: "USA PATRIOT Act",
    cfrRef: "",
    regLongName:
      "Uniting and Strengthening America by Providing Appropriate Tools Required to Intercept and Obstruct Terrorism (USA PATRIOT) Act of 2001",
    regDescription:
      "The purpose of the USA Patriot Act is to deter and punish terrorist acts in the United States and around the world. Section 314 helps law enforcement identify, disrupt, and prevent terrorist acts and money laundering activities by encouraging further cooperation among law enforcement, regulators, and financial institutions to share information.",
    regUrl: "https://www.law.cornell.edu/uscode/text/31/5318",
    regComplianceGuideUrl: "",
    regRelatedLaw: "USA PATRIOT Act of 2001",
    regEffectiveDate: null,
    regAuthoringRegulator: "USLEG",
    regPrimarySupervisor: "DOJ",
    status: true,
    createdDate: "2023-06-23T13:45:38.000Z",
    updatedDate: null,
    regulator: {
      id: 16,
      regulatorShortName: "USLEG",
      regulatorLongName: "US Legislature",
      regulatorDesc: "",
      regulatorMainUrl: "",
      regulatorUpdateSource: "",
      regulatorUpdateContact: "",
      country: "US",
      state: "All",
      county: "",
      status: true,
      createdDate: "2023-06-23T13:44:36.000Z",
      updatedDate: null,
    },
  },
  {
    id: 306,
    regId: "0306",
    regShortName: "Title 26 Tax",
    cfrRef: "",
    regLongName: "Internal Revenue Code",
    regDescription:
      "Title 26 provides for the conditions under which the IRS may disclose Federal Tax Returns and Return Information (FTI) to other agencies, including the Census Bureau.",
    regUrl: "https://www.law.cornell.edu/cfr/text/26/1.408-6",
    regComplianceGuideUrl: "",
    regRelatedLaw: "",
    regEffectiveDate: null,
    regAuthoringRegulator: "IRS",
    regPrimarySupervisor: "IRS",
    status: true,
    createdDate: "2023-06-23T13:45:38.000Z",
    updatedDate: null,
    regulator: {
      id: 11,
      regulatorShortName: "IRS",
      regulatorLongName: "US Internal Revenue Service",
      regulatorDesc:
        "The Internal Revenue Service is the revenue service for the United States federal government, which is responsible for collecting taxes and administering the Internal Revenue Code, the main body of the federal statutory tax law.",
      regulatorMainUrl: "https://www.irs.gov/",
      regulatorUpdateSource: "",
      regulatorUpdateContact: "",
      country: "US",
      state: "All",
      county: "",
      status: true,
      createdDate: "2023-06-23T13:44:36.000Z",
      updatedDate: null,
    },
  },
  {
    id: 305,
    regId: "0305",
    regShortName: "TCPA",
    cfrRef: "",
    regLongName: "Telephone Consumer Protection Act",
    regDescription:
      "The law restricts telemarketing certain phone calls, text messages, and facsimiles. It also places restrictions on the use of automatic dialing systems and artificial or prerecorded voice messages.",
    regUrl: "https://www.law.cornell.edu/cfr/text/47/64.1200",
    regComplianceGuideUrl: "",
    regRelatedLaw: "Telephone Consumer Protection Act of 1991",
    regEffectiveDate: null,
    regAuthoringRegulator: "USLEG",
    regPrimarySupervisor: "FTC",
    status: true,
    createdDate: "2023-06-23T13:45:38.000Z",
    updatedDate: null,
    regulator: {
      id: 16,
      regulatorShortName: "USLEG",
      regulatorLongName: "US Legislature",
      regulatorDesc: "",
      regulatorMainUrl: "",
      regulatorUpdateSource: "",
      regulatorUpdateContact: "",
      country: "US",
      state: "All",
      county: "",
      status: true,
      createdDate: "2023-06-23T13:44:36.000Z",
      updatedDate: null,
    },
  },
  {
    id: 304,
    regId: "0304",
    regShortName: "Securities Exchange Act of 1934",
    cfrRef: "17 CFR 240",
    regLongName: "Securities Exchange Act of 1934",
    regDescription:
      "The Securities Exchange Act of 1934 (SEA) was created to govern securities transactions on the secondary market, after issue, ensuring greater financial transparency and accuracy and less fraud or manipulation.",
    regUrl:
      "https://www.ecfr.gov/cgi-bin/text-idx?SID=165f89a0daaa46128e9bc8f3a35cbb2e&mc=true&node=pt17.4.240&rgn=div5",
    regComplianceGuideUrl:
      "https://www.nyse.com/publicdocs/nyse/regulation/nyse/sea34.pdf",
    regRelatedLaw: "Securities Exchange Act of 1934",
    regEffectiveDate: null,
    regAuthoringRegulator: "SEC",
    regPrimarySupervisor: "SEC",
    status: true,
    createdDate: "2023-06-23T13:45:38.000Z",
    updatedDate: null,
    regulator: {
      id: 15,
      regulatorShortName: "SEC",
      regulatorLongName: "Securities and Exchange Commission",
      regulatorDesc:
        "<p>The mission of the SEC is to protect investors; maintain fair, orderly, and efficient markets; and facilitate capital formation. The SEC strives to promote a market environment that is worthy of the public's trust.</p>",
      regulatorMainUrl: "https://www.sec.gov/",
      regulatorUpdateSource: "",
      regulatorUpdateContact: "",
      country: "All",
      state: "All",
      county: "",
      status: true,
      createdDate: "2023-06-23T13:44:36.000Z",
      updatedDate: "2023-07-04T05:46:44.000Z",
    },
  },
  {
    id: 303,
    regId: "0303",
    regShortName: "Securities Act of 1933",
    cfrRef: "17 CFR 230",
    regLongName: "Securities Act of 1933",
    regDescription:
      'The act—also known as the "Truth in Securities" law, the 1933 Act, and the Federal Securities Act—requires that investors receive financial information from securities being offered for public sale.',
    regUrl:
      "https://www.ecfr.gov/cgi-bin/text-idx?SID=165f89a0daaa46128e9bc8f3a35cbb2e&mc=true&node=pt17.3.230&rgn=div5",
    regComplianceGuideUrl:
      "https://www.govinfo.gov/content/pkg/COMPS-1884/pdf/COMPS-1884.pdf",
    regRelatedLaw: "Securities Act of 1933",
    regEffectiveDate: null,
    regAuthoringRegulator: "SEC",
    regPrimarySupervisor: "SEC",
    status: true,
    createdDate: "2023-06-23T13:45:38.000Z",
    updatedDate: null,
    regulator: {
      id: 15,
      regulatorShortName: "SEC",
      regulatorLongName: "Securities and Exchange Commission",
      regulatorDesc:
        "<p>The mission of the SEC is to protect investors; maintain fair, orderly, and efficient markets; and facilitate capital formation. The SEC strives to promote a market environment that is worthy of the public's trust.</p>",
      regulatorMainUrl: "https://www.sec.gov/",
      regulatorUpdateSource: "",
      regulatorUpdateContact: "",
      country: "All",
      state: "All",
      county: "",
      status: true,
      createdDate: "2023-06-23T13:44:36.000Z",
      updatedDate: "2023-07-04T05:46:44.000Z",
    },
  },
  {
    id: 302,
    regId: "0302",
    regShortName: "SCRA",
    cfrRef: "",
    regLongName: "Servicemembers Civil Relief Act",
    regDescription:
      "The SCRA is a law created to provide extra protections for servicemembers in the event that legal or financial transactions adversely affect their rights during military or uniformed service.",
    regUrl: "https://www.law.cornell.edu/uscode/text/50/chapter-50",
    regComplianceGuideUrl: "",
    regRelatedLaw: "Servicemembers Civil Relief Act",
    regEffectiveDate: null,
    regAuthoringRegulator: "USLEG",
    regPrimarySupervisor: "DOJ",
    status: true,
    createdDate: "2023-06-23T13:45:38.000Z",
    updatedDate: null,
    regulator: {
      id: 16,
      regulatorShortName: "USLEG",
      regulatorLongName: "US Legislature",
      regulatorDesc: "",
      regulatorMainUrl: "",
      regulatorUpdateSource: "",
      regulatorUpdateContact: "",
      country: "US",
      state: "All",
      county: "",
      status: true,
      createdDate: "2023-06-23T13:44:36.000Z",
      updatedDate: null,
    },
  },
  {
    id: 301,
    regId: "0301",
    regShortName: "SAFE Act",
    cfrRef: "",
    regLongName: "Secure and Fair Enforcement for Mortgage Licensing Act",
    regDescription:
      "The Secure and Fair Enforcement for Mortgage Licensing Act of 2008 (SAFE Act) was enacted on July 30, 2008, and mandates a nationwide licensing and registration system for residential mortgage loan originators (MLOs).",
    regUrl: "https://www.law.cornell.edu/cfr/text/12/part-1008",
    regComplianceGuideUrl:
      "https://files.consumerfinance.gov/f/201203_cfpb_update_SAFE_Act_Exam_Procedures.pdf",
    regRelatedLaw:
      "Secure and Fair Enforcement for Mortgage Licensing Act of 2008",
    regEffectiveDate: null,
    regAuthoringRegulator: "USLEG",
    regPrimarySupervisor: "CFPB",
    status: true,
    createdDate: "2023-06-23T13:45:38.000Z",
    updatedDate: null,
    regulator: {
      id: 16,
      regulatorShortName: "USLEG",
      regulatorLongName: "US Legislature",
      regulatorDesc: "",
      regulatorMainUrl: "",
      regulatorUpdateSource: "",
      regulatorUpdateContact: "",
      country: "US",
      state: "All",
      county: "",
      status: true,
      createdDate: "2023-06-23T13:44:36.000Z",
      updatedDate: null,
    },
  },
];
