export const pageData = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "Sed ac dui aliquam, efficitur sapien ut, consectetur nunc.",
  "Integer euismod purus vel libero vehicula congue.",
  "Vivamus ultrices quam eget dui eleifend, eu placerat tellus suscipit.",
  "Praesent ut felis ac mi congue ultrices.",
  "Fusce dignissim turpis eu ante fermentum cursus.",
  "Donec non sem non nisl tristique hendrerit.",
  "Nullam volutpat magna vitae nibh feugiat, id volutpat sapien ullamcorper.",
  "Cras tincidunt nunc id ipsum mattis, eget interdum mi commodo.",
  "Vestibulum in quam nec orci aliquet pellentesque.",
  "Maecenas consectetur velit nec odio commodo, et volutpat mauris lobortis.",
  "Phasellus vitae risus sed lorem elementum tincidunt.",
  "Ut non sapien malesuada, consequat nisi vitae, luctus sapien.",
  "Aenean vitae nunc dapibus, maximus nunc at, efficitur lacus.",
  "Quisque luctus elit at erat efficitur fringilla.",
  "In tincidunt leo non volutpat mattis.",
  "Morbi bibendum quam in enim varius ullamcorper.",
  "Vivamus pharetra felis et tincidunt vehicula.",
  "Suspendisse eget lorem vel nisi commodo bibendum.",
  "Pellentesque eleifend dui a ultrices congue.",
  "Nam et urna a ipsum efficitur dapibus.",
  "Curabitur fringilla risus sit amet justo consequat eleifend.",
  "Proin auctor enim sit amet turpis hendrerit iaculis.",
  "Aliquam rhoncus augue ac purus cursus, nec tristique eros consectetur.",
  "Vivamus a metus sed dolor consectetur cursus.",
  "Nulla sollicitudin odio vitae metus interdum consectetur.",
  "Fusce tristique ex vitae risus mattis, ut consectetur ligula tempus.",
  "Nunc et purus tristique, faucibus ipsum vel, feugiat ex.",
  "Sed fermentum lectus sed consectetur dignissim.",
  "Etiam sed urna sed ipsum dapibus sagittis.",
  "Phasellus vulputate libero sed ex tincidunt feugiat.",
];
